version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}

      # Install Dependencies and sroting in a virtual env
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"

      # Lint
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint --exit-zero *.py

      # DFS Tests (2)
      - run:
          name: DFS Tests
          command: |
            . venv/bin/activate
            python -m unittest

      # Coverage Report
      - run:
          name: Coverage Report
          command: |
            . venv/bin/activate
            coverage run *.py
            coverage report -m
