version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.2-stretch-browsers

    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}

      # Install Dependencies and sroting in a virtual env
      - run:
          name: Install Python deps in a venv
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements/dev.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements/dev.txt" }}
          paths:
            - "venv"

      # Lint
      - run:
          name: Lint
          command: |
            . venv/bin/activate
            pylint --exit-zero *.py
      - store_artifacts:
          path: lint-reports/
          destination: lint
      - store_test_results:
          path: lint-reports/
      # Maybe test the algorithms DFS, BFS & A* here later? Could be fun...